### ISSUE TITLE
Something syntax error in built SCSS file.

### ISSUE THREAD

**Issue by whitetrefoil** [ElementUI/theme-default-scss#2]
version 9694529

in `button.scss:291`:
```scss
    @each $type in (primary, success, warning, danger, info){

        .el-button--$type{ // <== This line

            &:first-child{

                border-right-color: rgba(#fff, 0.5);
            }
```

Which should be
```scss
    @each $type in (primary, success, warning, danger, info){

        .el-button--#{$type}{

            &:first-child{

                border-right-color: rgba(#fff, 0.5);
            }
```
